export const facilityData = [
  {
    id: "badminton-hall",
    sport: "Badminton",
    name: "Indoor Badminton Hall",
    type: "Court Cluster",
    setting: "Indoor",
    count: "7 synthetic courts",
    location: "New SAC / Gymkhana zone",
    timings: "6:00 AM - 10:00 PM",
    access: "IITB students and staff",
    note: "Centralised AC and professional-grade flooring.",
    features: ["Synthetic surface", "AC hall", "High demand evenings"],
    slots: ["06:00 AM", "07:30 AM", "05:30 PM", "08:00 PM"],
  },
  {
    id: "basketball-indoor",
    sport: "Basketball",
    name: "Indoor Basketball Arena",
    type: "Arena",
    setting: "Indoor",
    count: "Match-ready arena",
    location: "New SAC / Gymkhana complex",
    timings: "6:00 AM - 10:00 PM",
    access: "IITB students and staff",
    note: "Built for institute training sessions and competitive games.",
    features: ["Weather-safe", "Training space", "Spectator friendly"],
    slots: ["07:00 AM", "12:30 PM", "06:30 PM", "08:30 PM"],
  },
  {
    id: "football-turf",
    sport: "Football",
    name: "Football Ground and Turf",
    type: "Ground",
    setting: "Outdoor",
    count: "Main turf + futsal space",
    location: "Gymkhana / New Gymkhana opposite Hostel 11",
    timings: "6:00 AM - 10:00 PM",
    access: "IITB students and staff",
    note: "Floodlit and among the busiest evening facilities on campus.",
    features: ["Turf surface", "Floodlights", "Futsal-compatible"],
    slots: ["06:00 AM", "08:00 AM", "06:00 PM", "08:00 PM"],
  },
  {
    id: "tennis-courts",
    sport: "Lawn Tennis",
    name: "Tennis Courts",
    type: "Court Cluster",
    setting: "Outdoor",
    count: "Multiple synthetic and clay courts",
    location: "Near Gymkhana / SAC",
    timings: "6:00 AM - 10:00 PM",
    access: "IITB students and staff",
    note: "Recent additions expanded the playable court count.",
    features: ["Mixed surfaces", "Coaching friendly", "Good daylight use"],
    slots: ["06:30 AM", "08:30 AM", "05:00 PM", "07:00 PM"],
  },
  {
    id: "table-tennis-hall",
    sport: "Table Tennis",
    name: "Table Tennis Hall",
    type: "Hall",
    setting: "Indoor",
    count: "8 professional tables",
    location: "Gymkhana / New Gymkhana",
    timings: "6:00 AM - 10:00 PM",
    access: "IITB students and staff",
    note: "Air-conditioned setup with competition-ready tables.",
    features: ["AC hall", "8 Stag tables", "Fast turnover slots"],
    slots: ["07:00 AM", "01:00 PM", "05:00 PM", "08:30 PM"],
  },
  {
    id: "squash-courts",
    sport: "Squash",
    name: "Squash Courts",
    type: "Court Cluster",
    setting: "Indoor",
    count: "Dedicated squash courts",
    location: "SAC / Gymkhana",
    timings: "6:00 AM - 10:00 PM",
    access: "IITB students and staff",
    note: "Compact booking windows make these great between classes.",
    features: ["Indoor play", "Practice-focused", "Short sessions"],
    slots: ["06:30 AM", "11:00 AM", "06:30 PM", "09:00 PM"],
  },
  {
    id: "swimming-pools",
    sport: "Aquatics",
    name: "Swimming Pools",
    type: "Aquatics Complex",
    setting: "Indoor / Outdoor",
    count: "Olympic pool + training sections",
    location: "Near SAC / Gymkhana area",
    timings: "Morning and evening sessions",
    access: "IITB students and staff",
    note: "Supports swimming, diving, and water polo activity.",
    features: ["Olympic-sized pool", "Training lanes", "Aquatics support"],
    slots: ["06:00 AM", "07:00 AM", "05:30 PM", "07:00 PM"],
  },
  {
    id: "athletics-track",
    sport: "Athletics",
    name: "Athletics Track and Field",
    type: "Track",
    setting: "Outdoor",
    count: "400 m standard track",
    location: "Gymkhana main field",
    timings: "6:00 AM - 10:00 PM",
    access: "IITB students and staff",
    note: "Floodlit track with field event support.",
    features: ["Floodlit", "Track and field", "Warm-up friendly"],
    slots: ["06:00 AM", "07:30 AM", "06:00 PM", "08:00 PM"],
  },
  {
    id: "cricket-ground",
    sport: "Cricket",
    name: "Cricket Ground and Practice Pitches",
    type: "Ground",
    setting: "Outdoor",
    count: "Main ground + nets",
    location: "Gymkhana field",
    timings: "Daylight and scheduled sessions",
    access: "IITB students and staff",
    note: "Practice nets and match space sit in the same ecosystem.",
    features: ["Full-sized ground", "Practice pitches", "Team sessions"],
    slots: ["06:30 AM", "08:30 AM", "04:30 PM", "06:30 PM"],
  },
  {
    id: "volleyball-courts",
    sport: "Volleyball",
    name: "Volleyball Courts",
    type: "Court Cluster",
    setting: "Outdoor / Indoor",
    count: "Gymkhana courts + hostel courts",
    location: "Gymkhana and hostels",
    timings: "Morning to late evening",
    access: "IITB community",
    note: "Hostel-level courts make this one of the easiest sports to join.",
    features: ["Campus-wide access", "Casual and team play", "Quick registration"],
    slots: ["06:00 AM", "05:00 PM", "06:30 PM", "08:00 PM"],
  },
  {
    id: "gymkhana-field",
    sport: "Field Games",
    name: "Gymkhana Main Field / New Gymkhana",
    type: "Multi-use Ground",
    setting: "Outdoor",
    count: "Large multi-sport space",
    location: "Gymkhana hub / opposite Hostel 11",
    timings: "Extended hours depending on event use",
    access: "IITB students and staff",
    note: "Used across football, hockey, athletics, rugby, frisbee, and institute events.",
    features: ["Multi-use", "Large footprint", "Event-friendly"],
    slots: ["06:00 AM", "09:00 AM", "05:30 PM", "07:30 PM"],
  },
];

export const initialRegistrations = [
  {
    id: 1,
    name: "Aarav Mehta",
    facilityName: "Indoor Badminton Hall",
    sport: "Badminton",
    date: "2026-04-08",
    time: "07:30 AM",
    status: "registered",
  },
  {
    id: 2,
    name: "Sneha Kulkarni",
    facilityName: "Football Ground and Turf",
    sport: "Football",
    date: "2026-04-08",
    time: "06:00 PM",
    status: "waitlist",
  },
  {
    id: 3,
    name: "Harsh Vora",
    facilityName: "Table Tennis Hall",
    sport: "Table Tennis",
    date: "2026-04-09",
    time: "05:00 PM",
    status: "registered",
  },
];

export const officialLinks = [
  {
    title: "Gymkhana Sports Portal",
    href: "https://gymkhana.iitb.ac.in/sports/",
    note: "Official booking and sports information entry point.",
  },
  {
    title: "Court Status",
    href: "https://gymkhana.iitb.ac.in/sports/CourtStatus",
    note: "Check live court availability and facility mapping.",
  },
  {
    title: "IITB Sports",
    href: "https://gymkhana.iitb.ac.in/instiapp//org/gssa",
    note: "General sports body page, events, and updates.",
  },
];

export const statusTone = {
  registered: "status-registered",
  waitlist: "status-waitlist",
};

export const getToday = () => new Date().toISOString().slice(0, 10);
